#!/usr/bin/env python3

import openai
import os
import pyperclip
import pygame
from pydub import AudioSegment
from pydub.playback import play

your_openai_key = os.environ.get('OPENAI_KEY', '')  # Replace with your OpenAI API key
your_text = pyperclip.paste()  # Read the current clipboard content

client = openai.OpenAI(api_key=your_openai_key)

response = client.audio.speech.create(
  model="tts-1",
  voice="shimmer",  # other voices: 'cove', 'echo', 'fable', 'onyx', 'nova', 'shimmer'
  input=your_text
)

response.stream_to_file('speech.mp3')

# Change the playback speed using pydub
sound = AudioSegment.from_file('speech.mp3')
speed_changed_sound = sound.speedup(playback_speed=1.5, chunk_size=150, crossfade=25)

# Play the altered audio
play(speed_changed_sound)
